add newsl. (work: 53%)
BlackNinja10735/Project_3__Minimal_Team_1 pull request #2
Opened 2023-12-03 15:00 UTC by BlackNinja10735

2023-12-25 23:56 UTC, marianaD4 reviewed
При ширині екрану 375px є горизонтальний скрол
Немає валідації на email і зміни рамки 
На планшеті контейнер неправильний

2023-12-25 23:56 UTC, marianaD4 commented on index.html
> +                            <p class="newsletter-description__subtitle"><b>Every week we will send you new designs and information about sales.</b></p>
article всередині article  не найкращий варіант, краще просто div

2023-12-25 23:56 UTC, marianaD4 commented on index.html
> +                        <article class="newsletter-content">
div

2023-12-25 23:56 UTC, marianaD4 commented on index.html
> +                            <article class="newsletter-input">
div

2023-12-25 23:56 UTC, marianaD4 commented on sass/components/_newsletter.scss
> +    height: 848px;
не використовуємо фіксовану висоту для секцій

2023-12-25 23:56 UTC, marianaD4 commented on index.html
> +                                    <label class="newsletter-content-box__check-text">Agree to subscribe to the newsletter</label>
треба прив'язати label до input

2023-12-25 23:56 UTC, marianaD4 commented on index.html
> +                            <button class="newsletter-content__button">Send</button>
рамка у кнопки залишилась

2023-12-25 23:56 UTC, marianaD4 commented on sass/components/_newsletter.scss
> +    align-items: center;
зайвий код для mobile, по замовчуванню і так контент розміщується в колонку

2023-12-25 23:56 UTC, marianaD4 commented on sass/components/_newsletter.scss
> +        align-items: center;
для чого даний код? на всіх розширеннях блоки цього елементу в колонку розміщені

2023-12-25 23:56 UTC, marianaD4 commented on sass/components/_newsletter.scss
> +         width: 353px;
max-width краще використовувати

2023-12-25 23:56 UTC, marianaD4 commented on sass/components/_newsletter.scss
> +        align-items: center;
точно потрібен display: flex?

2023-12-26 17:06 UTC, BlackNinja10735 commented on sass/components/_newsletter.scss
> +    align-items: center;
він так не фіксується по центру

2024-01-02 10:12 UTC, marianaD4 requested changes

2024-01-02 10:12 UTC, marianaD4 commented on sass/components/_newsletter.scss
> +    align-items: center;
Тому що деякі елементи більші за екран + з'являється скрол
Переглянь, будь ласка, фіксовану ширину в першу чергу. Не може ж на екрані в 375px бути текст шириною 383px

 &-content{
        width: 393px;
        display: flex;
        justify-content: flex-start;
        flex-direction: column;

  &__subtitle{
            @include text;
            width: 383px;
            color: $main_color;
        }
        
Максимально старайся уникати фіксованих ширин, коли мова йде про 100% ширини контейнера. Краще використати max-width, якщо не вдається без фіксованої ширини

2024-01-02 10:12 UTC, marianaD4 commented on sass/components/_newsletter.scss
> +            width: 383px;
більше за ширину екрану

2024-01-02 10:12 UTC, marianaD4 commented on sass/components/_newsletter.scss
> +        width: 393px;
більше за ширину екрану

2024-01-09 10:29 UTC, marianaD4 reviewed
треба додати валідацію на форму

2024-01-09 10:31 UTC, marianaD4 commented on sass/components/_newsletter.scss
> +            width: 90%;
90%?

2024-01-09 10:31 UTC, marianaD4 commented on sass/components/_newsletter.scss
> +            height: 50px;
не додаємо фіксовану висоту для тексту

2024-01-09 10:31 UTC, marianaD4 commented on sass/components/_newsletter.scss
> +
зайві порожні рядки

2024-01-11 16:13 UTC, marianaD4 requested changes
немає валідації на неправильний email
прибираємо фіксовану висоту із загального блоку
перевір, щоб не було зайвих пропущених рядків

2024-01-11 16:13 UTC, marianaD4 commented on sass/components/_newsletter.scss
> +        height: 1055px;
ФІКСОВАНА ВИСОТА)))

2024-01-12 18:33 UTC, marianaD4 commented
![image](https://github.com/BlackNinja10735/Project_3__Minimal_Team_1/assets/124216656/2a21beea-a7a5-4613-9a18-fc7ca5b9038b)

2024-01-18 17:52 UTC, merged